#!/usr/bin/env python3
"""
Generate all paper figures into figures/ from committed result artifacts.

Every recovery share, dollar figure, and correlation in every figure is read
from a committed artifact (results JSON, frozen run manifest, or
ccf_data.json regenerated by make_ccf_data.py); no such number is hardcoded
here. tools/liveness_gates.py zero-greps this module for the known
benchmark-share literals (post-freeze consistency pass).

Run:  python3 figures/make_figures.py            # all figures
      python3 figures/make_figures.py fig1 fig2  # a subset
"""

from __future__ import annotations

import json
from pathlib import Path

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import FancyBboxPatch

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "figures"
DPI = 220

# Okabe-Ito colorblind-safe palette, keyed by paradigm
C_CHOICE = "#D55E00"    # household-choice (ABM family) — vermillion
C_SURV = "#0072B2"      # loan-level survival (hazard) — blue
C_CROSS = "#CC79A7"     # cross-design hybrids — purple
C_GRAY = "#7f7f7f"

plt.rcParams.update({
    "font.size": 10.5, "axes.titlesize": 12, "axes.titleweight": "bold",
    "axes.spines.top": False, "axes.spines.right": False,
    "figure.facecolor": "white",
})


def _j(rel: str):
    return json.load(open(ROOT / rel))


# --- Committed artifacts (single source for every displayed number) --------
SHARED = _j("hazard/data/shared_layer_scoring_results.json")["results"]
PATHA_HEADLINE = _j(
    "hazard/data/runs/run-2026-07-14-pathA-seasonal/manifest.json")["headline"]
FOLDIN = _j("abm/data/runs/run-2026-07-04-15yr-foldin/manifest.json")["metrics"]
BERGER = _j("abm/data/runs/run-2026-07-05-berger/manifest.json")["metrics"]
CROSS = _j("abm/data/cross_design_results.json")
SYNTH = _j("hazard/data/synthetic_companion_results.json")["two_by_two"]
FULLBOOK = _j("hazard/data/full_book_weighting_results.json")
EXT_LIT = _j("hazard/data/extension_risk_results_literature_microsim.json")

BENCH_B = SHARED["path_a"]["empirical_trapped_b"]
# Common netting delta (standalone minus shared basis); basis-invariant across
# estimators because the netting is common (§VII.F).
NETTING_PP = (SHARED["path_a"]["standalone_share_pct"]
              - SHARED["path_a"]["share_pct"])


def fig1_recovery_dotplot():
    """Recovery-by-estimator dot plot (manuscript recovery figure)."""
    pa = SHARED["path_a"]
    pb_comp = SHARED["path_b_fullbook_composed"]
    pb_cent = SHARED["path_b_central"]
    synth_b = SYNTH["hazard_synthetic_pathB"]
    recal = CROSS["variants"]["recalibrated"]
    frozen = CROSS["variants"]["frozen"]
    rows = [  # (label, shared-basis share %, r_lag0, paradigm color, standalone %)
        ("Path A — cohort GLM (fitted survival)",
         pa["share_pct"], PATHA_HEADLINE["r_lag0"], C_SURV,
         pa["standalone_share_pct"]),
        ("Path B — composed (SOMA coupon mix, shared layer)",
         pb_comp["share_pct"],
         FULLBOOK["path_b"]["full_book_weighted"]["cpr_r_lag0"], C_SURV,
         pb_comp["standalone_share_pct"]),
        ("Path B — literature microsim",
         pb_cent["share_pct"], EXT_LIT["cross_correlation"]["0"], C_SURV,
         pb_cent["standalone_share_pct"]),
        ("Path B — fully synthetic population",
         synth_b["share_pct"] - NETTING_PP, synth_b["cpr_r_lag0"], C_SURV,
         synth_b["share_pct"]),
        ("Cross-design ABM — recalibrated",
         recal["share_pct"], recal["cpr_r_lag0"], C_CROSS, None),
        ("Cross-design ABM — frozen calibration",
         frozen["share_pct"], frozen["cpr_r_lag0"], C_CROSS, None),
        # Production ABM row = the fold-in run Table 2 quotes; earlier
        # editions showed the Berger-run native-gate variant here.
        ("ABM — production (household choice)",
         FOLDIN["dollars_b"]["share_explained_pct"],
         FOLDIN["cross_correlation"]["0"], C_CHOICE, None),
    ]
    fig, ax = plt.subplots(figsize=(10.4, 4.8))
    ys = np.arange(len(rows))[::-1]
    for y, (label, share, r0, color, standalone) in zip(ys, rows):
        ax.plot([0, share], [y, y], color="#dddddd", lw=1.4, zorder=1)
        ax.scatter([share], [y], s=150, zorder=3,
                   facecolor=color, edgecolor=color, linewidth=2.0)
        note = f"{share:.1f}%" + (f" ({standalone:.1f})" if standalone else "")
        ax.annotate(note + f"   r₀={r0:+.2f}",
                    (share, y), xytext=(8, 0), textcoords="offset points",
                    va="center", fontsize=9.5, color="black")
    ax.axvline(100, color=C_GRAY, lw=1.2, ls="--", zorder=0)
    ax.text(100, len(rows) - 0.25, f" 100% of ${BENCH_B:.1f}B benchmark",
            color=C_GRAY, fontsize=9, va="bottom")
    ax.set_yticks(ys)
    ax.set_yticklabels([r[0] for r in rows], fontsize=10)
    ax.set_xlabel(f"Share of ${BENCH_B:.1f}B empirical trapped liquidity "
                  "recovered (%)\n"
                  "shared accounting basis — standalone-scorer values in "
                  "parentheses")
    ax.set_xlim(0, 185)
    handles = [
        plt.Line2D([], [], marker="o", ls="", mfc=C_SURV, mec=C_SURV, ms=10,
                   label="loan-level survival"),
        plt.Line2D([], [], marker="o", ls="", mfc=C_CROSS, mec=C_CROSS, ms=10,
                   label="cross-design (real covariates → ABM)"),
        plt.Line2D([], [], marker="o", ls="", mfc=C_CHOICE, mec=C_CHOICE, ms=10,
                   label="household choice (ABM)"),
    ]
    ax.legend(handles=handles, loc="lower right", fontsize=8.6, frameon=False)
    fig.text(0.005, 0.03,
             "Raw lag-0 correlations (r₀) annotated for reference only: once "
             "the shared trend is removed no estimator's co-movement is",
             fontsize=8, color=C_GRAY)
    fig.text(0.005, 0.005,
             "positive (detrended r: ABM −0.30, Path A −0.29, Path B −0.20; "
             "§V.C).",
             fontsize=8, color=C_GRAY)
    fig.tight_layout(rect=(0, 0.055, 1, 1))
    fig.savefig(OUT / "fig1_recovery_by_estimator.png", dpi=DPI)
    plt.close(fig)


def fig2_ccf():
    """Cross-correlation functions, ±6 monthly lags (manuscript CCF figure)."""
    d = _j("figures/ccf_data.json")
    series = [
        ("ABM (household choice)", d["abm"], C_CHOICE, "o"),
        ("Path A — cohort GLM", d["path_a"], C_SURV, "s"),
        ("Path B — literature microsim", d["path_b"], "#009E73", "D"),
    ]
    fig, ax = plt.subplots(figsize=(8.2, 4.6))
    ax.axvspan(-6.5, 0, color="#f0f0f0", zorder=0)
    ax.text(-6.2, -0.56, "lags < 0: empirical series leads; simulated path "
            "trails", fontsize=8.8, color=C_GRAY)
    for label, ccf, color, marker in series:
        lags = sorted(int(k) for k in ccf)
        ax.plot(lags, [ccf[str(k)] for k in lags],
                marker=marker, ms=5, lw=1.8, color=color, label=label)
    ax.axhline(0, color="black", lw=0.8)
    ax.axvline(0, color=C_GRAY, lw=0.8, ls=":")
    ax.set_xlabel("Lag (months); a peak at negative lag means the empirical "
                  "series leads\nand the simulated path trails (§V.C)")
    ax.set_ylabel("Cross-correlation")
    ax.set_xlim(-6.5, 6.5)
    ax.set_ylim(-0.6, 0.75)
    ax.set_xticks(range(-6, 7))
    ax.legend(loc="lower right", fontsize=9, frameon=False)
    fig.text(0.005, 0.005,
             "No timing evidence is claimed for any estimator: peak-lag "
             "moving-block intervals span zero, and the β₁ = 0 null shares "
             "Path B's −3 peak.", fontsize=8, color=C_GRAY)
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(OUT / "fig2_ccf.png", dpi=DPI)
    plt.close(fig)


def fig3_abm_waterfall():
    """ABM falsification bridge: every extension moves away from 100%."""
    early = _j("figures/fig3_stage_levels.json")["stages"]
    stages = [(s["label"], s["share_pct"]) for s in early]
    stages.append(("+ 15yr fold-in\n(production headline)",
                   FOLDIN["dollars_b"]["share_explained_pct"]))
    stages.append(("Native 15yr gate\n(Berger-run variant)",
                   BERGER["dollars_b"]["share_explained_pct"]))
    fig, ax = plt.subplots(figsize=(8.8, 4.8))
    xs = np.arange(len(stages))
    prev = None
    for x, (label, val) in zip(xs, stages):
        if prev is None:
            ax.bar(x, val, width=0.62, color=C_CHOICE, alpha=0.85)
            ax.text(x, val + 1.5, f"{val:.1f}%", ha="center", fontsize=10,
                    fontweight="bold")
        else:
            delta = val - prev
            ax.bar(x, delta, bottom=prev, width=0.62,
                   color="#a63603" if delta < 0 else "#1a9850", alpha=0.85)
            ax.plot([x - 1 + 0.31, x - 0.31], [prev, prev],
                    color=C_GRAY, lw=1.0, ls=":")
            ax.text(x, max(val, prev) + 1.5, f"{val:.1f}%", ha="center",
                    fontsize=10, fontweight="bold")
            if abs(delta) >= 3:  # in-bar label only when it fits
                ax.text(x, prev + delta / 2, f"{delta:+.1f}", ha="center",
                        va="center", fontsize=8.6, color="white",
                        fontweight="bold")
            else:
                ax.text(x + 0.36, prev + delta / 2, f"{delta:+.1f}",
                        ha="left", va="center", fontsize=8.6, color="#a63603")
        prev = val
    ax.axhline(100, color=C_GRAY, lw=1.2, ls="--")
    ax.text(len(stages) - 0.4, 101.5, "benchmark (100%)", color=C_GRAY,
            fontsize=9, ha="right")
    ax.set_xticks(xs)
    ax.set_xticklabels([s[0] for s in stages], fontsize=8.8)
    ax.set_ylabel(f"Share of ${BENCH_B:.1f}B benchmark explained (%)")
    ax.set_ylim(0, 112)
    fig.text(0.005, 0.005,
             "Each extension was pre-registered with an expected direction and "
             "moved the ABM away from 100% — the residual is not missing "
             "household behavior (§VI).",
             fontsize=8, color=C_GRAY)
    fig.tight_layout(rect=(0, 0.045, 1, 1))
    fig.savefig(OUT / "fig3_abm_waterfall.png", dpi=DPI)
    plt.close(fig)


def fig4_refi_sweep():
    """Institutional gap vs assumed U.S.-transplant refi CPR (§20.1)."""
    d = _j("abm/data/refi_sweep_results.json")
    x = [r["refi_inplace_cpr"] * 100 for r in d["sweep"]]
    g_abm = [r["gap_abm_b"] for r in d["sweep"]]
    g_pb = [r["gap_pathB_b"] for r in d["sweep"]]
    be_abm = d["breakeven_refi"]["abm"] * 100
    be_pb = d["breakeven_refi"]["path_b"] * 100

    fig, ax = plt.subplots(figsize=(8.2, 4.8))
    ax.axhline(0, color="black", lw=1.0)
    ax.plot(x, g_abm, "o-", color=C_CHOICE, lw=2, label="ABM")
    ax.plot(x, g_pb, "s-", color=C_SURV, lw=2, label="Path B (hybrid pipeline)")
    for be, color, dy in ((be_abm, C_CHOICE, -60), (be_pb, C_SURV, 60)):
        ax.axvline(be, color=color, lw=1.0, ls=":")
        ax.annotate(f"breakeven {be:.1f}%", xy=(be, 0), xytext=(be + 0.4, dy),
                    fontsize=9, color=color,
                    arrowprops=dict(arrowstyle="->", color=color, lw=1.0))
    ax.annotate("best estimate ≈ 0\n(Berger ~1bp GE result)", xy=(0, g_pb[0]),
                xytext=(1.4, -560), fontsize=9, color="black",
                arrowprops=dict(arrowstyle="->", lw=1.0))
    ax.axvspan(17.0, 18.4, color="#f0f0f0", zorder=0)
    ax.text(17.7, -650, "PE reduced-form\nceiling (rejected)", fontsize=8,
            color=C_GRAY, ha="center")
    ax.set_xlabel("Assumed U.S.-transplant refinance-in-place CPR (%/yr)")
    ax.set_ylabel("Institutional gap, U.S. − Danish ($B)")
    ax.legend(loc="upper left", fontsize=9.5, frameon=False)
    fig.text(0.005, 0.005,
             "Positive gap = U.S. par-payoff traps more than Danish buyback. "
             f"Path B flips sign at {be_pb:.1f}% refi — the honest claim is "
             "gap ≈ 0, not robustly negative (§20.1).",
             fontsize=8, color=C_GRAY)
    fig.tight_layout(rect=(0, 0.04, 1, 1))
    fig.savefig(OUT / "fig4_institutional_gap_sensitivity.png", dpi=DPI)
    plt.close(fig)


def fig5_cross_design_bars():
    """Cross-design variants: recovery AND path correlation together."""
    pre = CROSS["preregistration"]
    recal = CROSS["variants"]["recalibrated"]
    frozen = CROSS["variants"]["frozen"]
    cats = ["Synthetic control\n(production baseline)",
            "Frozen calibration\n(real covariates)",
            "Recalibrated\n(real covariates)"]
    shares = [CROSS["synthetic_control"]["share_pct"],
              frozen["share_pct"], recal["share_pct"]]
    # cross_design_results.json carries no lag-0 r for the synthetic control;
    # the production fold-in manifest is its committed source.
    corrs = [FOLDIN["cross_correlation"]["0"],
             frozen["cpr_r_lag0"], recal["cpr_r_lag0"]]
    colors = [C_CHOICE, C_CROSS, C_CROSS]
    threshold = pre["undercuts_paradigm_above_pct"]
    band_lo, band_hi = pre["corroborates_band_pct"]

    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(9.2, 4.3))
    xs = np.arange(len(cats))
    ax1.axhspan(band_lo, band_hi, color="#eef3f8", zorder=0)
    ax1.text(2.45, band_hi - 1.6, "synthetic-ABM band", fontsize=7.8,
             color=C_SURV, ha="right", va="top")
    ax1.axhline(threshold, color=C_GRAY, lw=1.1, ls="--")
    ax1.text(-0.42, threshold + 1.5,
             f"pre-registered {threshold:.0f}% threshold",
             fontsize=8, color=C_GRAY)
    ax1.bar(xs, shares, width=0.6, color=colors, alpha=0.9)
    for x, s in zip(xs, shares):
        ax1.text(x, s + 1.2, f"{s:.1f}%", ha="center", fontsize=10,
                 fontweight="bold")
    ax1.set_xticks(xs); ax1.set_xticklabels(cats, fontsize=8.4)
    ax1.set_ylabel("Share of benchmark recovered (%)")
    ax1.set_ylim(0, 68)

    ax2.axhline(0, color="black", lw=0.9)
    ax2.bar(xs, corrs, width=0.6, color=colors, alpha=0.9)
    for x, c in zip(xs, corrs):
        ax2.text(x, c - 0.018, f"{c:+.3f}", ha="center", va="top", fontsize=10,
                 fontweight="bold")
    ax2.set_xticks(xs); ax2.set_xticklabels(cats, fontsize=8.4)
    ax2.set_ylabel("CPR path correlation, lag 0")
    ax2.set_ylim(-0.45, 0.12)

    fig.text(0.005, 0.005,
             f"Recalibration lifts recovery to {recal['share_pct']:.1f}%; "
             "neither variant shows positive contemporaneous path alignment.",
             fontsize=8, color=C_GRAY)
    fig.tight_layout(rect=(0, 0.045, 1, 1))
    fig.savefig(OUT / "fig5_cross_design.png", dpi=DPI)
    plt.close(fig)


def fig6_elasticity_band():
    """Path B trapped liquidity across the Rothstein P_q band."""
    d = _j("hazard/data/extension_risk_band_literature.json")
    pts = sorted(((float(k), v["trapped_b"], v["share_pct"])
                  for k, v in d["results"].items()))
    x = [p[0] for p in pts]; y = [p[1] for p in pts]
    fig, ax = plt.subplots(figsize=(7.2, 4.2))
    ax.fill_between(x, y, min(y) - 12, color="#d6e6f2", alpha=0.7, zorder=0)
    ax.plot(x, y, "o-", color=C_SURV, lw=2)
    ax.scatter([6.5], [dict(zip(x, y))[6.5]], s=170, zorder=4,
               facecolor="white", edgecolor=C_SURV, linewidth=2.2)
    for xi, yi, si in pts:
        ax.annotate(f"${yi:.0f}B ({si:.1f}%)", (xi, yi), xytext=(0, 9),
                    textcoords="offset points", ha="center", fontsize=9.3)
    ax.axhline(BENCH_B, color=C_GRAY, lw=1.2, ls="--")
    ax.text(x[0], BENCH_B + 2.8, f"empirical benchmark ${BENCH_B:.1f}B",
            fontsize=8.8, color=C_GRAY)
    ax.annotate("central estimate (6.5%)", xy=(6.5, dict(zip(x, y))[6.5]),
                xytext=(6.62, 806), fontsize=9, color=C_SURV,
                arrowprops=dict(arrowstyle="->", color=C_SURV, lw=1.0))
    ax.set_xlabel("Liebersohn–Rothstein quarterly mobility decline per 100bp, "
                  "$P_q$ shock (%)")
    ax.set_ylabel("Path B trapped liquidity ($B)")
    ax.set_ylim(755, 845)
    fig.tight_layout()
    fig.savefig(OUT / "fig6_elasticity_band.png", dpi=DPI)
    plt.close(fig)


def _box(ax, x, y, w, h, text, fc, fontsize=8.8, tc="black"):
    ax.add_patch(FancyBboxPatch((x, y), w, h, boxstyle="round,pad=0.012",
                                fc=fc, ec="#555555", lw=1.0))
    ax.text(x + w / 2, y + h / 2, text, ha="center", va="center",
            fontsize=fontsize, color=tc)


def fig7_architecture():
    """One-panel roadmap of the two-estimator architecture."""
    fig, ax = plt.subplots(figsize=(9.6, 5.4))
    ax.set_xlim(0, 10); ax.set_ylim(0, 10); ax.axis("off")

    # Data sources (left column)
    _box(ax, 0.2, 7.6, 2.5, 1.5,
         "FRED + NY Fed SOMA\nrates, holdings,\ncoupon cohorts", "#fff3e0")
    _box(ax, 0.2, 5.4, 2.5, 1.5,
         "Freddie Mac loan level\n75k stratified sample\n(2017–2021)", "#fff3e0")
    _box(ax, 0.2, 3.2, 2.5, 1.5,
         "Literature priors\nPSA, Rothstein band,\nBerger et al. (Danish)", "#fff3e0")

    # Estimators (middle column)
    _box(ax, 3.6, 7.4, 2.9, 1.7,
         "ABM — household choice\n10k agents, DTI / loss-aversion /\n"
         "wait-and-see gates → CPR surface", "#fde5d8")
    _box(ax, 3.6, 5.2, 2.9, 1.7,
         "Path A — fitted survival\nPoisson GLM, 295 stratum FE\n"
         "(cohort-month panel)", "#dce9f5")
    _box(ax, 3.6, 3.0, 2.9, 1.7,
         "Path B — literature survival\n75k-loan microsim, competing\n"
         "risks, Markov servicer pipeline", "#dce9f5")

    # Shared accounting + benchmark (right column)
    _box(ax, 7.3, 5.2, 2.4, 1.9,
         "Shared macro accounting\ncommon QT window\n(2022-06 → 2025-11),\n"
         "phased cap, SOMA balance", "#eeeeee")
    _box(ax, 7.3, 2.6, 2.4, 1.6,
         f"Benchmark comparison\n${BENCH_B:.1f}B empirical\ntrapped liquidity",
         "#e8f0e4", fontsize=9.2)

    def arrow(x0, y0, x1, y1, color="#555555", ls="-"):
        ax.annotate("", xy=(x1, y1), xytext=(x0, y0),
                    arrowprops=dict(arrowstyle="->", color=color, lw=1.3, ls=ls))

    arrow(2.7, 8.35, 3.6, 8.25)                     # FRED/SOMA -> ABM
    arrow(1.45, 7.6, 7.3, 6.9)                      # FRED/SOMA -> shared acct
    ax.text(4.9, 7.12, "macro series", fontsize=7.2, color="#555555",
            rotation=-6)
    arrow(2.7, 6.15, 3.6, 6.05)                     # Freddie -> Path A
    arrow(2.7, 5.9, 3.6, 3.95)                      # Freddie -> Path B
    arrow(2.7, 3.95, 3.6, 3.6)                      # priors -> Path B
    arrow(6.5, 8.25, 7.55, 6.9)                     # ABM -> shared
    arrow(6.5, 6.05, 7.3, 6.1)                      # A -> shared
    arrow(6.5, 3.85, 7.55, 5.3)                     # B -> shared
    arrow(8.5, 5.2, 8.5, 4.2)                       # shared -> benchmark

    # Robustness cross-links (dashed)
    arrow(2.7, 5.7, 3.7, 7.4, color=C_CROSS, ls="--")
    ax.text(2.05, 6.98, "cross-design: real\ncovariates → ABM (§15)",
            fontsize=7.6, color=C_CROSS, ha="right")
    arrow(1.45, 3.2, 3.9, 3.0, color="#009E73", ls="--")
    ax.text(1.28, 2.55, "symmetric companion: fully synthetic\n"
            "population → hazard (§18)", fontsize=7.6, color="#009E73")

    abm_share = FOLDIN["dollars_b"]["share_explained_pct"]
    pa_share = PATHA_HEADLINE["share_pct"]
    pb_share = EXT_LIT["share_explained_pct"]
    ax.text(5.0, 0.6,
            f"Recovery, standalone scorer: ABM {abm_share:.1f}% · "
            f"Path A {pa_share:.1f}% · Path B {pb_share:.1f}% "
            "(survival recovers the benchmark; household choice does not)",
            ha="center", fontsize=9, color=C_GRAY)
    fig.tight_layout()
    fig.savefig(OUT / "fig7_architecture.png", dpi=DPI)
    plt.close(fig)


GENERATORS = {
    "fig1": fig1_recovery_dotplot,
    "fig2": fig2_ccf,
    "fig3": fig3_abm_waterfall,
    "fig4": fig4_refi_sweep,
    "fig5": fig5_cross_design_bars,
    "fig6": fig6_elasticity_band,
    "fig7": fig7_architecture,
}

if __name__ == "__main__":
    import sys
    OUT.mkdir(exist_ok=True)
    names = sys.argv[1:] or list(GENERATORS)
    for name in names:
        GENERATORS[name]()
        print(f"  built {name} ({GENERATORS[name].__name__})")
    print(f"Figures written to {OUT}")
